// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyU2s4MTuxULpnRJpMJY0gHBiVTKMkaQ',
    appId: '1:512296810727:web:b8aa341ca671fb7b4c4a42',
    messagingSenderId: '512296810727',
    projectId: 'controle-abastecimento-35666',
    authDomain: 'controle-abastecimento-35666.firebaseapp.com',
    storageBucket: 'controle-abastecimento-35666.firebasestorage.app',
    measurementId: 'G-HT2ZB7GR3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs_MMRiC77g43FBrb-P75z7HHL-FHCqws',
    appId: '1:512296810727:android:fba06e954db8cf3c4c4a42',
    messagingSenderId: '512296810727',
    projectId: 'controle-abastecimento-35666',
    storageBucket: 'controle-abastecimento-35666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbfZQq_Il04H20jx2JcY4NaOGOhdGGLM',
    appId: '1:512296810727:ios:02a4bd85005847ee4c4a42',
    messagingSenderId: '512296810727',
    projectId: 'controle-abastecimento-35666',
    storageBucket: 'controle-abastecimento-35666.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVbfZQq_Il04H20jx2JcY4NaOGOhdGGLM',
    appId: '1:512296810727:ios:02a4bd85005847ee4c4a42',
    messagingSenderId: '512296810727',
    projectId: 'controle-abastecimento-35666',
    storageBucket: 'controle-abastecimento-35666.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApyU2s4MTuxULpnRJpMJY0gHBiVTKMkaQ',
    appId: '1:512296810727:web:ea35e268bfdf39524c4a42',
    messagingSenderId: '512296810727',
    projectId: 'controle-abastecimento-35666',
    authDomain: 'controle-abastecimento-35666.firebaseapp.com',
    storageBucket: 'controle-abastecimento-35666.firebasestorage.app',
    measurementId: 'G-ZFJF5SXG3P',
  );
}
